blog/urls.py
from django.conf.urls import url
from .views import ArticleList, article_details, CreateArticle, UpdateArticle, \
    DeleteArticle, YearlyOrdered,  MonthlyOrdered, ArticleDetails


urlpatterns = [
    url(r'^create/$', CreateArticle.as_view(), name="blog_article_create"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/update/$',
         UpdateArticle.as_view(), name="blog_article_update"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/delete/$', DeleteArticle.as_view(), name="blog_article_delete"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/$', ArticleDetails.as_view(), name="blog_article_details"),
    url(r'^(?P<year>\d{4})/$', YearlyOrdered.as_view(), name='yearly_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', MonthlyOrdered.as_view(), name='monthly_archive'),
    url(r'^$', ArticleList.as_view(), name="blog_article_list"),
]

smartblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from centralizer.urls import company as co_urls, tag as tag_urls
from blog import urls as blurls
from contact import urls as curls
from django.views.generic import RedirectView, TemplateView
from user import urls as user_urls

urlpatterns = [
    url(r'^user/', include(user_urls, app_name='user', namespace='dj-auth')),
    url(r'^admin/', include(admin.site.urls)),
    #nu mai pui $ la sfarsit, atentie atentie atentie!!!
    #url(r'^related/', include(rel_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^company/', include(co_urls)),
    #url(r'^page', include(flurl)),
    url(r'^blog/', include(blurls)),
    url(r'^contact/', include(curls)),
    #nici aici nu pui $ la sfarsit, you have been warned
    url(r'^$', RedirectView.as_view(pattern_name='blog_article_list', permanent=False)),
    url(r'^about/$', TemplateView.as_view(template_name='site/about.html'), name='about_section'),
]

centralizer/models.py
from django.db import models
from datetime import date
from django.core.urlresolvers import reverse

# Create your models here.
class Tag(models.Model):
    tagid = models.AutoField(
        primary_key=True,
        serialize=False,
        verbose_name='tagid',
        auto_created=True
    )
    tagname = models.CharField(max_length=31, unique=True)
    tag_slug = models.SlugField()
    added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.tagname.title()

    class Meta:
        ordering = ['tagname']

    def get_absolute_url(self):
        return reverse('centralizer_tagdetails', kwargs={"slug":self.tag_slug})
    
    def get_update_url(self):
        return reverse('centralizer_update_tag', kwargs={"slug":self.tag_slug})
    
    def get_delete_url(self):
        return reverse('centralizer_delete_tag', kwargs={"slug":self.tag_slug})

    def published_articles(self):
        return self.articles.filter(added__lt=date.today())


class Company(models.Model):
    companyid = models.AutoField(
        primary_key=True,
        serialize=False,
        verbose_name='compid',
        auto_created=True
    )
    company_name = models.CharField(max_length=31)
    company_slug = models.SlugField(max_length=31, unique=True, help_text="Label for URL composition")
    description = models.TextField()
    founded_date = models.DateField('date when it was founded')
    email = models.EmailField()
    website = models.URLField(max_length=255)
    added = models.DateField(auto_now_add=True)
    # It is entirely up to you where you define the many to many relationship, related_type --> the name
    # to refer from the other table to this one, like t.companies (t short for tags) or c.tags (c short for company)
    tags = models.ManyToManyField(Tag, related_name='companies', blank=True)

    def __str__(self):
        return self.company_name

    class Meta:
        ordering = ['company_name']
        get_latest_by = 'founded_date'

    #aici ai nevoie de name-ul din urls pentru fiecare url, ca sa faci reverse url cu slug-ul, pentru crea link-uri intre pagini
    def get_absolute_url(self):
        return reverse('centralizer_company_details', kwargs={"slug": self.company_slug})
    
    def get_update_url(self):
        return reverse('centralizer_company_update', kwargs={"slug": self.company_slug})
    
    def get_delete_url(self):
        return reverse("centralizer_company_delete", kwargs={"slug": self.company_slug})

    def get_relnews_create_url(self):
        return reverse('centralizer_create_news', kwargs={"company_slug": self.company_slug})

class RelatedNews(models.Model):
    title = models.CharField(max_length=63)
    pub_date = models.DateField('date published')
    newslink = models.URLField(max_length=255)
    company = models.ForeignKey(Company, related_name='related_news', )
    news_slug = models.SlugField(max_length=63, blank=True)

    def get_absolute_url(self):
        return self.company.get_absolute_url()
    
    def get_delete_url(self):
        return reverse('centralizer_delete_news', kwargs={'company_slug': self.company.company_slug, 'news_slug': self.news_slug})

    def get_update_url(self):
        return reverse('centralizer_update_news', kwargs={'company_slug': self.company.company_slug, 'news_slug': self.news_slug})

    def __str__(self):
        #self.company calls the str (string) method of the company object
        return "{}:{}",format(self.company, self.title)

    class Meta:
        #verbose = change the display string of a class
        unique_together = ('news_slug', 'company')
        verbose_name = "related news"
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'

centralizer/forms.py
from django.forms import ModelForm
from .models import Tag, Company, RelatedNews
from django.core.exceptions import ValidationError
from django.forms.widgets import HiddenInput

#importam modelele si le traducem in obiecte-formular echivalente
# in Meta definim ce model si ce campuri ale acelui model sunt folosite de un anume formular

class SlugMixin():
#A class mixin for the clean_slug for tag and company method
    def clean_slug(self):
        slug = (self.cleaned_data['elem_slug'].lower())
        if slug == "create":
            raise ValidationError("You can't give the slug the name 'create' !")
        return slug

class TagForms(ModelForm, SlugMixin):
    class Meta:
        model = Tag
        fields = "__all__"

    def clean_tagname(self):
        return self.cleaned_data['tagname'].lower()



class CompanyForms(ModelForm, SlugMixin):
    class Meta:
        model = Company
        fields = '__all__'

    def clean_company_name(self):
        return self.cleaned_data['company_name'].lower()


class NewsForm(ModelForm, SlugMixin):
    class Meta:
        model = RelatedNews
        fields = '__all__'
        widgets = {'company': HiddenInput()}

    def clean_title(self):
        return self.cleaned_data['title'].lower()

    def save(self, **kwargs):
        '''
        company_obj = kwargs.get('company_obj', None)
        if company_obj is not None:
            instance = super().save(commit=False)
            instance.company = company_obj
            instance.save()
            self.save_m2m()
        else:
            instance = super().save()
        return instance
        '''
        instance = super().save(commit=False)
        instance.company = (self.data.get('company'))
        instance.save()
        self.save_m2m()
        return instance

    def clean(self):
        cleaned_data = super().clean()
        news_slug = cleaned_data.get('news_slug')
        company_obj = self.data.get('company')
        isthere = (RelatedNews.objects.filter(news_slug__iexact=news_slug, company=company_obj).exists())
        if isthere:
            raise ValidationError("This entrance is already in the database")
        else:
            return cleaned_data

centralizer/views.py
from django.shortcuts import render
from django.http.response import HttpResponse, Http404
from django.template import Context, loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, render, redirect, reverse
from .forms import TagForms, CompanyForms, NewsForm
from django.views.generic import View, DetailView, DeleteView, ListView, CreateView
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.contrib.auth import PermissionDenied
from django.contrib.auth.decorators import user_passes_test
#from .utils import ViewObjectsMixin, UpdateObjectsMixin, DeleteObjectMixin, ViewDetails, CreateViewForm
from .models import RelatedNews
# Create your views here.
#we are already in centralizer, so we don't need call centralizer.models
from .models import Tag, Company
from django.urls.base import reverse_lazy
from core.utils import UpdateView
from .utils import PageLinksMixin, GetRelatedObjectMixin, CompanyMixin #RelatedFormMixin
from user.decorators import custom_login_required, require_authenticated_permission, class_login_required

@require_authenticated_permission(
    'centralizer.add_relatednews')
class RelatedNewsCreate(GetRelatedObjectMixin, CompanyMixin, CreateView):
    form_class = NewsForm
    model = RelatedNews

    def get_initial(self):
        company_slug = self.kwargs.get(
            self.company_slug_url_kwarg)
        self.company = get_object_or_404(
            Company, slug__iexact=company_slug)
        initial = {
            self.company_context_object_name:
                self.company,
        }
        initial.update(self.initial)
        return initial


@require_authenticated_permission(
    'centralizer.delete_relatednews')
class RelatedNewsDelete(
        GetRelatedObjectMixin,
        CompanyMixin,
        CreateView):
    form_class = NewsForm
    model = RelatedNews
    slug_url_kwarg = 'related_slug'

    def get_success_url(self):
        return (self.object.company
                .get_absolute_url())


@require_authenticated_permission(
    'centralizer.change_relatednews')
class RelatedNewsUpdate(
        GetRelatedObjectMixin,
        CompanyMixin,
        CreateView):
    form_class = NewsForm
    model = RelatedNews
    slug_url_kwarg = 'related_slug'


@require_authenticated_permission(
    'centralizer.add_company')
class CompanyCreate(CreateView):
    form_class = CompanyForms
    model = Company


@require_authenticated_permission(
    'company.delete_company')
class CompanyDelete(DeleteView):
    model = Company
    success_url = reverse_lazy(
        'centralizer_company_list')


class CompanyDetail(DetailView):
    model = Company


class CompanyList(PageLinksMixin, ListView):
    model = Company
    paginate_by = 5  # 5 items per page


@require_authenticated_permission(
    'centralizer.change_company')
class CompanyUpdate(UpdateView):
    form_class = CompanyForms
    model = Company


@require_authenticated_permission(
    'centralizer.add_tag')
class TagCreate(CreateView):
    form_class = TagForm
    model = Tag


@require_authenticated_permission(
    'centralizer.delete_tag')
class TagDelete(DeleteView):
    model = Tag
    success_url = reverse_lazy(
        'centralizer_tag_list')


class TagDetail(DetailView):
    model = Tag


class TagList(PageLinksMixin, ListView):
    paginate_by = 5
    model = Tag


@require_authenticated_permission(
    'centralizer.change_tag')
class TagUpdate(UpdateView):
    form_class = TagForms
    model = Tag

templates/centralizer/base_centralizer.html
{% extends parent_template|default:"base.html" %}
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'centralizer/style.css' %}" />
{% endblock %}
{% block content %}
<div class="row">
<section class="eight columns">
    {% block original %}
        This is the old
    {% endblock %}
</section>

<section class="desktop four columns">
    {% block create %}
    {% endblock %}
</section>
</div>
{% endblock %}

{% block footer %}
    {% if is_paginated %}
        <div class="row">
        <div class="twelve columns">
        <ul class="pagination">
            {% if previous_page_url %}
                <li>
                <a href="{{ previous_page_url }}">Previous</a>
                </li>
            {% endif %}
                {% if first_page_url %}
            <li>
            <a href="{{ first_page_url }}">First Page</a>
            </li>
        {% endif %}
        <li>
            Page: {{ page_obj.number }}
            of: {{ paginator.num_pages }}
        </li>
        {% if next_page_url %}
            <li>
            <a href="{{ next_page_url }}">
                Next
            </a>
            </li>
        {% endif %}
        {% if last_page_url %}
            <li>
            <a href="{{ last_page_url }}">Last Page</a>
            </li>
        {% endif %}
        </ul>
        </div>
        </div>
    {% endif %}
{% endblock %}

templates/centralizer/company_det.html
{% extends parent_template|default:"base.html" %}
{% block title %}
{# Overrides parent block #}
{{  block.super }} - Company Details
{% endblock %}
{% block content %}
<article>
<h2>{{ company.company_name }}</h2>
<dl>
    <dt>Founded</dt>
{# The date bellow is considered a datetime object, being equivalent with {{ company.founded_date|date }}#}
    <dd>{{ company.founded_date }}</dd>
    <dt>Website</dt>
    <dd>{{ company.founded_date|date:"F jS, Y" }}</dd>
    <dt>Website</dt>
    <dd><a href="{{ company.website|urlize }}">{{ company.website }}</a></dd>
    <dt>Email Address</dt>
    <dd>{{ company.email }}</dd>

    <dt>Tag{{ company.tags.count|pluralize }}</dt>
    {% for tag in company.tags.all %}
    <dd><a href="{{ tag.get_absolute_url }}">{{ tag.tagname|title }}</a> </dd>
    {% endfor %}
</dl>

{{ company.description|linebreaks }}

{% if company.relatednews_set.all %}
<section>
    <h3>Related News</h3>
    <ul>
        {% for news in company.relatednews_set.all %}
        <li>
            <a href="{{ news.get_absolute_url }}">
                {{ news.tile|title }}
            </a>
        </li>
        <li>
	    <a href="{{ news.get_delete_url }}">
	      Delete News
	    </a>
	</li>
        {% endfor %}        
    </ul>
<ul>
    <li>
        <a href="{{ relatednews.get_update_url }}">
            Edit Related
        </a>
    </li>
</ul>
</section>
{% endif %}

{% if company.articles.all %}
    <section>
    <h3>
        Article{{ company.article.count|pluralize }}
    </h3>
    <ul>
        {% for art in company.articles.all %}
        <li>
            <a href="{{ art.get_absolute_url}}">
                {{ art.title|title }}
            </a>
        </li>
        {% endfor %}
    </ul>
    </section>
{% endif %}
</article>

<p>
<a href="{% url 'centralizer_create_related' %}">Create Related News</a>
</p>
<ul><li>
<a href="{{company.get_update_url}}">Edit Company</a>
</li></ul>
{% endblock %}

templates/centralizer/company_details.html
{% extends parent_template|default:"base.html" %}
{% block title %}
{# Overrides parent block #}
{{  block.super }} - Company Details
{% endblock %}
{% block content %}
<article>
<h2>{{ company.company_name }}</h2>
<dl>
    <dt>Founded</dt>
{# The date bellow is considered a datetime object, being equivalent with {{ company.founded_date|date }}#}
    <dd>{{ company.founded_date }}</dd>
    <dt>Website</dt>
    <dd>{{ company.founded_date|date:"F jS, Y" }}</dd>
    <dt>Website</dt>
    <dd><a href="{{ company.website|urlize }}">{{ company.website }}</a></dd>
    <dt>Email Address</dt>
    <dd>{{ company.email }}</dd>

    <dt>Tag{{ company.tags.count|pluralize }}</dt>
    {% for tag in company.tags.all %}
    <dd><a href="{{ tag.get_absolute_url }}">{{ tag.tagname|title }}</a> </dd>
    {% endfor %}
</dl>

{{ company.description|linebreaks }}
{% if company.relatednews_set.all or company.articles.all or perms.centralizer.add_relatednews %}
{% if company.relatednews_set.all %}
<section>
    <h3>Related News</h3>
    <ul>
        {% for news in company.relatednews_set.all %}
        <li>
            <a href="{{ news.get_absolute_url }}">
                {{ news.tile|title }}
            </a>
        </li>
        <li>
	    <a href="{{ news.get_delete_url }}">
	      Delete News
	    </a>
	</li>
    <li>
        <a href="{{ relatednews.get_update_url }}">
            Edit Related
        </a>
    </li>
        {% endfor %}
</ul>
<p>
    <a href="{{ company.get_relnews_create_url }}" class="button">
        Add News
    </a>
</p>
</section>
{% endif %}

{% if company.related_news.all or perms.blog.view_future_article and company.articles.all or company.articles|length > 0 or perms.centralizer.add_relatednews %}
    <section class="meta offset-by-two one-third column">
    <h3>
        Article{{ company.article.count|pluralize }}
    </h3>
    <ul>
        {% for art in company.articles.all %}
        <li>
            <a href="{{ art.get_absolute_url}}">
                {{ art.title|title }}
            </a>
        </li>
        {% endfor %}
    </ul>
    </section>
    {% else %}
    <section class="meta offset-by-two two-thirds column">
    </section>
{% endif %}
{% endif %}
</article>

<p>
<a href="{{ company.centralizer_create_related }}">Create Related News</a>
</p>
<ul><li>
<a href="{{company.centralizer_update_company}}">Edit Company</a>
</li></ul>
{% endblock %}

templates/centralizer/company_list.html
{% extends parent_template|default:"centralizer/base_centralizer.html" %}
{% block title %}
{# Overrides parent block #}
{{  block.super }} - List of Companies - {{ tag.tagname|title }}
{% endblock %}
{% block original %}
<h2>Company List</h2>
    <div class="mobile">
    {% block new_button %}
    <a href="{% url 'centralizer_create_company' %}" class="button button-primary">Create a new company</a>
    {% endblock %}
    </div>

   {% if has_pages %}
    <ul>
    {% if previous_page %}
    <li>
    <a href="{{ previous_page }}">Previous</a>
    </li>
{% endif%}

{% if next_page %}
    <li>
    <a href="{{ next_page }}">Next</a>
    </li>
{% endif%}
    </ul>
    {% endif %}
<ul>
<li>
    Page {{ company_list.number }}
    of {{ paginator.num_pages }}
</li>

    {% for comp in company_list %}
    <li>
        <a href="{{ comp.get_absolute_url }}">
            {{ comp.company_name }}
        </a>
        {% empty %}
        <li><em>No companies here</em></li>
    {% endfor %}
</ul>
<ul><li>
<a href="{{company.get_update_url}}">Edit Company</a>
</li>
<li>
<a href="{{company.get_delete_url}}">Delete Tag</a>
</li>
</ul>
{% endblock %}

{% block footer %}
{% endblock %}

templates/centralizer/compcreate.html
{% extends parent_template|default:"centralizer/base_centralizer.html" %}
{% block title %}
{{ block.super }} - Create Company
{% endblock %}
{% block content %}
    <div>
    <div>
    <form action="{% url 'centralizer_create_company' %}" method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            Create Company
        </button>
    </form>
    </div>
    </div>
{% endblock %}

templates/centralizer/compdel.html
{% extends parent_template|default: "centralizer/base_centralizer.html"%}
{% block title %}
{{ block.super }} - Delete The Tag
{% endblock %}
{% block content %}
    <div>
    <div>
        <form action="{{ company.delcompany }}" method="post">
            {% csrf_token %}
            <p>
                Really Delete {{ tag.tagname }}?
            </p>
            <a href="{{ tag.get_absolute_url }}">Cancel</a>
        <button type="submit">Delete</button>
        </form>
    </div>
    </div>
{% endblock %}

templates/centralizer/compupdate.html
{% extends parent_template|default:"centralizer/base_centralizer.html" %}
{% block title %}
{{ block.super }} - Update Company
{% endblock %}

{% block content %}
    <div>
    <div>
        <form action="{{ company.upcomp }}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Update the Company
            </button>
        </form>
    </div>
    </div>
{% endblock %}

templates/centralizer/relnewscreate.html
{% extends parent_template|default:"centralizer/base_centralizer.html" %}
{% block title %}
{{ block.super }} - Create Related News Reference
{% endblock %}
{% block content %}
    <div>
    <div>
    <form action="{% company.get_relnews_create_url %}" method="post">
    {% csrf_token %}
        {{ theform.as_p }}
        <button type="submit">
            Create News
        </button>
    </form>
    </div>
    </div>
{% endblock %}

templates/centralizer/relnewsdel.html
{% extends parent_template|default: "centralizer/base_centralizer.html"%}
{% block title %}
{{ block.super }} - Delete Related News
{% endblock %}
{% block content %}
    <div>
    <div>
        <form action="{{ related.delrel }}" method="post">
            {% csrf_token %}
            <p>
                Really Delete {{ related.title }}?
            </p>
            <a href="{{ related.get_absolute_url }}">Cancel</a>
        <button type="submit">Delete</button>
        </form>
    </div>
    </div>
{% endblock %}

templates/centralizer/relnewsup.html
{% extends parent_template|default:"centralizer/base_centralizer.html" %}
{% block title %}
{{ block.super }} - Update Related News
{% endblock %}

{% block content %}
    <div>
    <div>
        <form action="{{ relnews.upnews }}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Update Related
            </button>
        </form>
    </div>
    </div>
{% endblock %}

templates/centralizer/tag_details.html
{% extends parent_template|default:"base.html" %}
{% block title %}
{# Overrides parent block #}
{{  block.super }} - Tag Details
{% endblock %}
{% block content %}
{# we use the pipe simbol to apply filters to variables (like capitilize the names and titles) #}
<h2> {{ tag.tagname|title }} </h2><!-- name of tag -->
{% if not tag.companies.all and not tag.articles.all %}
    {% if not tag.companies.all %}
    <p>This tag is not associated with any company</p>
{% else %}
    <p>Tag is associated with
    {{ tag.companies.count }}
    compan{{ tag.companies.count|pluralize:"y,ies" }}.
    </p>
<section>
    <h3>Compan{{ tag.companies.count|pluralize:"y,ies" }}</h3>
    <ul><!-- list of companies related to the tag -->
        {# in Django we remove the parantheses from the method .all() ==> .all #}
        {% for comp in tag.companies.all %}
            {# We don't capitalize the company name, because it may have customize capitalization #}
            <li><a href="{{ comp.get_absolute_url }}"> {{ comp.company_name }} </a></li>
        {% endfor %}
        {# don't forget to close the for, because in templates we have scope #}
    </ul>
</section>
{% endif %}
    {% if not tag.articles.all %}
        <p>This tag is not associated with any article</p>
    {% else %}
    {% if perms.blog.view_future_article %}

<section>
    <h3>Articles</h3>
    <ul><!-- list of articles related to the tag -->
        {% for art in tag.articles.all %}
            {# we use the pipe simbol to apply filters to variables (like capitilize the names and titles) #}
            <li><a href=""> {{ art.title|title }} </a></li>
        {% endfor %}
    </ul>
</section>
{% endif %}

    <p>This tag has no content associated to it</p>
{% endif %}
    {% if perms.centralizer.change_tag or perms.centralizer.delete_tag %}
<ul><li>
<a href="{{tag.get_update_url}}">Edit Tag</a>
</li>
<li>
<a href="{{tag.get_delete_url}}">Delete Tag</a>
</li></ul>
    {% endif %}
    {% endif %}
{% endblock %}

templates/centralizer/tagdetails.html
{% extends parent_template|default:"base.html" %}
{% block title %}
{# Overrides parent block #}
{{  block.super }} - Tag Details
{% endblock %}
{% block content %}
{# we use the pipe simbol to apply filters to variables (like capitilize the names and titles) #}
<h2> {{ tag.tagname|title }} </h2><!-- name of tag -->
{% if tag.companies.all %}
    <p>Tag is associated with
    {{ tag.companies.count }}
    compan{{ tag.companies.count|pluralize:"y,ies" }}.
    </p>
<section>
    <h3>Compan{{ tag.companies.count|pluralize:"y,ies" }}</h3>
    <ul><!-- list of companies related to the tag -->
        {# in Django we remove the parantheses from the method .all() ==> .all #}
        {% for comp in tag.companies.all %}
            {# We don't capitalize the company name, because it may have customize capitalization #}
            <li><a href="{{ comp.get_absolute_url }}"> {{ comp.company_name }} </a></li>
        {% endfor %}
        {# don't forget to close the for, because in templates we have scope #}
    </ul>
</section>
{% endif %}
{% if tag.articles.all %}
<section>
    <h3>Articles</h3>
    <ul><!-- list of articles related to the tag -->
        {% for art in tag.articles.all %}
            {# we use the pipe simbol to apply filters to variables (like capitilize the names and titles) #}
            <li><a href=""> {{ art.title|title }} </a></li>
        {% endfor %}
    </ul>
</section>
{% endif %}
{% if not tag.companies.all and not tag.articles.all %}
    <p>This tag has no content associated to it</p>
{% endif %}
<ul><li>
<a href="{{tag.get_update_url}}">Edit Tag</a>
</li>
<li>
<a href="{{tag.get_delete_url}}">Delete Tag</a>
</li></ul>
{% endblock %}

templates/centralizer/taglist.html
{% extends parent_template|default:"centralizer/base_centralizer.html" %}
{% block title %}
{# Extends parent block #}
{{  block.super }} - List of Tags
{% endblock %}
{# Start the content block defined in base #}
{% block content %}
<h1>One</h1>
<h2>List of Tags</h2>
{% if has_pages %}
    <ul>
    {% if prev_page %}
    <li>
        <a href="{{ prev_page }}">
            Previous Tag
        </a>
    </li>
    {% endif %}
    {% if next_page %}
    <li>
        <a href="{{ next_page }}">
            Next Tag
        </a>
    </li>
    {% endif %}
    </ul>
    {% endif %}

<div>
<a href="{% url 'centralizer_create_tag' %}">Create New Tag</a>
</div>
<ul>
    {% for tag in tag_list %}
    <li>
        <a href="{{ tag.get_absolute_url }}">
            {{ tag.tagname|title }}
        </a>
    </li>
        {% empty %}
        <li><em>There are no Tags available</em></li>
    {% endfor %}
</ul>
{# End content block defined in base #}
<ul><li>
<a href="{{tag.get_update_url}}">Edit Tag</a>
</li></ul>
{% endblock %}

{% block footer %}
{% endblock %}

templates/centralizer/tagupdate.html
{% extends parent_template|default:"centralizer/base_centralizer.html" %}
{% block title %}
{{ block.super }} - Update Tag
{% endblock %}

{% block content %}
    <div>
    <div>
        <form action="{{ tag.uptag }}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Update the Tag
            </button>
        </form>
    </div>
    </div>
{% endblock %}