blog/urls.py
from django.conf.urls import url
from .views import ArticleList, article_details, CreateArticle, UpdateArticle, \
    DeleteArticle, YearlyOrdered,  MonthlyOrdered, ArticleDetails


urlpatterns = [
    url(r'^create/$', CreateArticle.as_view(), name="blog_article_create"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/update/$',
         UpdateArticle.as_view(), name="blog_article_update"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/delete/$', DeleteArticle.as_view(), name="blog_article_delete"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/$', ArticleDetails.as_view(), name="blog_article_details"),
    url(r'^(?P<year>\d{4})/$', YearlyOrdered.as_view(), name='yearly_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', MonthlyOrdered.as_view(), name='monthly_archive'),
    url(r'^$', ArticleList.as_view(), name="blog_article_list"),
]

smartblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from centralizer.urls import company as co_urls, tag as tag_urls
from blog import urls as blurls
from contact import urls as curls
from django.views.generic import RedirectView, TemplateView
from user import urls as user_urls

urlpatterns = [
    url(r'^user/', include(user_urls, app_name='user', namespace='dj-auth')),
    url(r'^admin/', include(admin.site.urls)),
    #nu mai pui $ la sfarsit, atentie atentie atentie!!!
    #url(r'^related/', include(rel_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^company/', include(co_urls)),
    #url(r'^page', include(flurl)),
    url(r'^blog/', include(blurls)),
    url(r'^contact/', include(curls)),
    #nici aici nu pui $ la sfarsit, you have been warned
    url(r'^$', RedirectView.as_view(pattern_name='blog_article_list', permanent=False)),
    url(r'^about/$', TemplateView.as_view(template_name='site/about.html'), name='about_section'),
]

user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView, TemplateView
from .views import DisableAccount, ActivateAccount, CreateAccount, ResendActivationEmail
from django.core.urlresolvers import reverse_lazy
from .views import DisableAccount

password_urls = [
    url(r'^change/$', auth_views.password_change, {
        'template_name': 'user/change_password_template.html',
        'post_change_redirect': reverse_lazy('dj-auth:pw_change')},
        name='pw-change'),
    url(r'^change/done/$', auth_views.password_change_done, {
        'template_name': 'user/password_change_done.html'},
        name='dj-auth:pw_change_done'),
    url(r'^$', RedirectView.as_view(pattern_name='dj-auth:pw_reset_start', permanent=False)),
]

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='dj-auth:login', permanent=False)),
    url(r'^login/$', auth_views.login, {'template_name': 'user/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'user/logged_out.html',
         'extra_context': {'form': AuthenticationForm}}, name='logout'),
    url(r'^password/', include(password_urls)),
    url(r'^reset/$', auth_views.password_reset,{
            'template_name':'user/password_reset_form.html',
            'email_template_name':'user/password_reset_email.txt',
            'subject_template_name':'user/password_reset_subject.txt',
            'post_reset_redirect':reverse_lazy('dj-auth:pw_reset_start'),
        }, name='pw_reset_start'),
    url(r'^reset/sent/$', auth_views.password_change_done, {
        'template_name': 'user/password_reset_sent.html',},
        name='pw_reset_sent'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,{
            'template_name': 'user/password_reset_confirm.html',
            'post_reset_redirect': reverse_lazy('dj-auth:pw_reset_complete')
        }, name='pw_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,{
        'template_name': 'user/password_reset_complete.html',
        'extra_content': {'form': AuthenticationForm}
    }, name='pw_reset_complete'),
    url(r'^disable/$', DisableAccount.as_view(), name='disable'),
    url(r'^create/done/$', TemplateView.as_view(), template_name='user/user_create_done.html', name='create_done'),
    url(r'^create/$', CreateAccount.as_view(), name='create'),
    url(r'^activate/(?P<uid64>[0-9A-Za-z_\-]+)/(?P<token>[0-9-A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    ActivateAccount.as_view(), name='activate'),
    url(r'^activate/resend/$', ResendActivationEmail.as_view(), name='resend_activation'),
    url(r'^activate', RedirectView.as_view(pattern_name='dj-auth:resend_activation', permanent=False)),
    ]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
            {% block title %}Companies{% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'site/normalize.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'site/skeleton.css' %}"/>
<!--     {#  #} block head %} -->
<!--     {#  #} endblock %} -->
</head>
<body>
{% load flatpages %}
{% get_flatpages as flatpages %}
<div class="container">
    <header class="row">
    <img src="{% static 'site/favicon.png' %}" alt="Favicon">
    <div class="offset-by-one ten columns">
    <h1 class="logo">Company Centralizer</h1>
        <main>
            {% block content %}
            This is the default content
            {% endblock %}
        </main>
    </div>
    </header>
    </div>
<div class="status row">
    <div class="offset-by-eight four columns">
        <ul class="inline">
            {% if user.is_authenticated %}
                <li><a href="{% url 'dj-auth:logout' %}?next={{ request.path }}" >Log out </a></li>
                {% else %}
                <li>
                <a href="{% url 'dj-auth:login' %}?next={{ request.path }}">Log in</a>
                </li>
            {% endif %}
        <li><a href="{% url 'dj-auth:create' %}">Register a New Account</a> </li>
        </ul>
    </div>
</div>

<div>
    <p>
        Some notes at the end
    </p>
</div>

<nav>
    <ul>
        {% for pg in flatpages %}
            <li>
            <a href="{{ pg.get_absolute_url }}">
                {{ pg.title }}
            </a>
            </li>
        {% endfor %}
        <li>
            <a href="{% url 'blog_article_list' %}">
                Articles
            </a>
        </li>
        <li>
            <a href="{% url 'centralizer_company_list' %}">
                Companies
            </a>
        </li>
        <li>
            <a href="{% url 'centralizer_taglist' %}">
                Tags
            </a>
        </li>
        <li>
	    <a href="{% url 'contact' %}">Contact Us</a>
        </li>
        <li>
	    <a href="{% url 'about_section' %}">About</a>
        </li>
    </ul>
</nav>

{% if messages %}
<div class="row">
<div class="twelve columns">
<ul class="messages">
{% for mes in messages %}
{% if mes.tags %}
<li class="{{mes.tags}}">
{%else%}
<li>
{%endif%}
{{message}}</li>
{%endfor%}
</ul>
</div>
</div>

{% endif %}

</body>
</html>