blog/urls.py
from django.conf.urls import url
from .views import ArticleList, article_details, CreateArticle, UpdateArticle, \
    DeleteArticle, YearlyOrdered,  MonthlyOrdered, ArticleDetails


urlpatterns = [
    url(r'^create/$', CreateArticle.as_view(), name="blog_article_create"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/update/$',
         UpdateArticle.as_view(), name="blog_article_update"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/delete/$', DeleteArticle.as_view(), name="blog_article_delete"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[\w\-]+)/$', ArticleDetails.as_view(), name="blog_article_details"),
    url(r'^(?P<year>\d{4})/$', YearlyOrdered.as_view(), name='yearly_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', MonthlyOrdered.as_view(), name='monthly_archive'),
    url(r'^$', ArticleList.as_view(), name="blog_article_list"),
]

smartblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from centralizer.urls import company as co_urls, tag as tag_urls
from blog import urls as blurls
from contact import urls as curls
from django.views.generic import RedirectView, TemplateView
from user import urls as user_urls

urlpatterns = [
    url(r'^user/', include(user_urls, app_name='user', namespace='dj-auth')),
    url(r'^admin/', include(admin.site.urls)),
    #nu mai pui $ la sfarsit, atentie atentie atentie!!!
    #url(r'^related/', include(rel_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^company/', include(co_urls)),
    #url(r'^page', include(flurl)),
    url(r'^blog/', include(blurls)),
    url(r'^contact/', include(curls)),
    #nici aici nu pui $ la sfarsit, you have been warned
    url(r'^$', RedirectView.as_view(pattern_name='blog_article_list', permanent=False)),
    url(r'^about/$', TemplateView.as_view(template_name='site/about.html'), name='about_section'),
]

user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView, TemplateView
from .views import DisableAccount, ActivateAccount, CreateAccount, ResendActivationEmail
from django.core.urlresolvers import reverse_lazy
from .views import DisableAccount

password_urls = [
    url(r'^change/$', auth_views.password_change, {
        'template_name': 'user/change_password_template.html',
        'post_change_redirect': reverse_lazy('dj-auth:pw_change')},
        name='pw-change'),
    url(r'^change/done/$', auth_views.password_change_done, {
        'template_name': 'user/password_change_done.html'},
        name='dj-auth:pw_change_done'),
    url(r'^$', RedirectView.as_view(pattern_name='dj-auth:pw_reset_start', permanent=False)),
]

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='dj-auth:login', permanent=False)),
    url(r'^login/$', auth_views.login, {'template_name': 'user/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'user/logged_out.html',
         'extra_context': {'form': AuthenticationForm}}, name='logout'),
    url(r'^password/', include(password_urls)),
    url(r'^reset/$', auth_views.password_reset,{
            'template_name':'user/password_reset_form.html',
            'email_template_name':'user/password_reset_email.txt',
            'subject_template_name':'user/password_reset_subject.txt',
            'post_reset_redirect':reverse_lazy('dj-auth:pw_reset_start'),
        }, name='pw_reset_start'),
    url(r'^reset/sent/$', auth_views.password_change_done, {
        'template_name': 'user/password_reset_sent.html',},
        name='pw_reset_sent'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,{
            'template_name': 'user/password_reset_confirm.html',
            'post_reset_redirect': reverse_lazy('dj-auth:pw_reset_complete')
        }, name='pw_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,{
        'template_name': 'user/password_reset_complete.html',
        'extra_content': {'form': AuthenticationForm}
    }, name='pw_reset_complete'),
    url(r'^disable/$', DisableAccount.as_view(), name='disable'),
    url(r'^create/done/$', TemplateView.as_view(), template_name='user/user_create_done.html', name='create_done'),
    url(r'^create/$', CreateAccount.as_view(), name='create'),
    url(r'^activate/(?P<uid64>[0-9A-Za-z_\-]+)/(?P<token>[0-9-A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    ActivateAccount.as_view(), name='activate'),
    url(r'^activate/resend/$', ResendActivationEmail.as_view(), name='resend_activation'),
    url(r'^activate', RedirectView.as_view(pattern_name='dj-auth:resend_activation', permanent=False)),
    ]

user/models.py
from django.db import models
from django.conf import settings

class Profile(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL)
    slug=models.SlugField(max_length=30, unique=True)
    about=models.TextField()
    
    def __str__(self):
        return self.user.get_username()

# Create your models here.

user/forms.py
import logging
from django import forms
from django.contrib.auth.forms import UserCreationForm as BSUserCreationForm
from django.contrib.auth import get_user_model
from .utils import ActivationMailFormMixin

logger = logging.getLogger(__name__)


class UserCreationForm(BSUserCreationForm, ActivationMailFormMixin):

    class Meta(BSUserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email')
        mail_validation_error = ('User created. Could not send email to activate account')

        def save(self, **kwargs):
            user = super().save(commit=False)
            if not user.pk:
                user.is_active = False
                send_mail = True
            else:
                send_mail = False
            user.save()
            #save many-tomany relations
            self.save_m2m()
            if send_mail:
                self.send_mail(user=user, **kwargs)
                return user

class ResendActivationEmailForm(ActivationMailFormMixin, forms.Form):
    email = forms.EmailField()

    mail_validation_error = ('Couldn\'t resent activation email, please try again later')
    
    def save(self, **kwargs):
        User = get_user_model()
        try:
            user = User.objects.get(email=self.cleaned_data['emil'])
        except:
            logger.warning("The user with email {} does not exist".format(self.cleaned_data['email']))
            return None
        self.send_mail(user=user, **kwargs)
        return user

user/views.py
from django.shortcuts import render
from django.contrib.auth import get_user, logout, get_user_model, logout
from django.utils.encoding import force_text
from django.contrib.messages import error, success
from django.contrib.auth.tokens import default_token_generator as def_token
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.core.urlresolvers import reverse_lazy
from .forms import UserCreationForm, ResendActivationEmailForm
from .utils import MailContextViewMixin
from django.views.generic import View


#TemplateResponse is usually used in Auth instead of HttpResponse
class DisableAccount(View):
    success_url = settings.LOGIN_REDIRECT_URL
    template_name = ('user/user_confirm_delete.html')
    success_url = settings.LOGIN_REDIRECT_URL
    template_name = ('user/user_confirm_delete.html')

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def get(self, request):
        return TemplateResponse(request, self.template_name)

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def post(self, request):
        user = get_user(request)
        user.set_unusable_password()
        user.is_active = False
        user.save()
        logout()
        return redirect(self.success_url)

class CreateAccount(MailContextViewMixin, View):

    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(request, self.template_name, {'form': self.form_class()})

    #for the post method we use a special decorator for sensitive information, like passwords, so they won't be displayed
    #in the event of an error log or something
    @method_decorator(csrf_protect)
    @method_decorator(sensitive_post_parameters('password', 'password_confirm'))
    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            bound_form.save(**self.get_save_kwargs(request))
        if bound_form.mail_sent:
           return redirect(self.succress_url)
        else:
            error = (bound_form.non_field_errors())
            for er in error:
                error(request, er)
                return redirect('dj-auth:resend_activation')
        return TemplateResponse(self.template_name, {'form': bound_form})

class ActivateAccount(View):
    success_url = reverse_lazy('dj-auth:login')
    template_name = 'user/user_activate.html'

    @method_decorator(never_cache)
    def get(self, request, uidb64, token):
        User = get_user_model()
        try:
            uid = force_text(urlsafe_base64_encode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user=None
        if (user is not None and def_token.check_token(user, token)):
            user.is_active = True
            user.save()
            success(request, 'User is active, login')
            return redirect(self.success_url)
        else:
            return TemplateResponse(request, self.template_name)
        
class ResendActivationEmail(MailContextViewMixin, View):
    form_class = ResendActivationEmailForm
    success_url = reverse_lazy('dj-auth:login')
    template_name = 'user/resend_activation.html'
    
    @method_decorator(csrf_protect)
    def get(self, request):
        #forma clasica, bine ar fi s-o memorezi un pic
        return TemplateResponse(request, self.template_name, {'form': self.form_class})
    
    @method_decorator(csrf_protect)
    def post(self, request):
        #bounduim formularul, iar ar fi bine s-o stii pe asta
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            user = bound_form.save(**self.get_save_kwargs(request))
            success(request, 'Activation Email Sent')
            return redirect(self.success_url)
        if (user is not None and not bound_form.mail_sent):
            err = (bound_form.non_field_errors())
            for er in err:
                error(request, er)
            if err:
                bound_form.errors.pop('__all__')
        return TemplateResponse(request, self.template_name, {'form': bound_form})
        
        
        
    

templates/user/base_user.html
{% extends parent_template|default:"base.html" %}

templates/user/logged_out.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Logged Out
{% endblock %}

{% block content %}
    <div class="row">
    <div class="offset-by-two eight columns">
        <p>You've successfully logged out.</p>
        {% include "user/login_form.html" with login_button='Log Back In' %}
    </div>
    </div>
{% endblock %}

templates/user/login.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
    {{ block.super }} - Login
{% endblock %}

{% block content %}
    <div class="row">
    <div class="offset-by-two five columns">
        {% include "user/login_form.html" %}
    </div>
    </div>
    <div class="three columns">
    <ul class="task-list">
        <li><a href="{% url 'dj-auth:pw_reset_start' %}">Password reset</a></li>
        <li><a href="{% url 'dj-auth:resend_activation' %}">If you lost your activation email</a></li>
    </ul>
    </div>
{% endblock %}

templates/user/login_form.html
<form action="{% url 'dj-auth:login' %}" method="post">
{% csrf_token %}
{{ form.as_p }}
    {% if next %}
        <input type="hidden" name="next" value="{{ next }}">
    {% endif %}
<button type="submit">{{ login_button|default:"Log in" }}</button>
</form>

templates/user/password_change_done.html
{% extends parent_template|default: 'user/base_user.html' %}
{% block title %}
    {{  block.super }} - Change Password
{% endblock %}

{% block content %}
    <div class="row">
    <div class="offset-by-two eight columns">
        <p>Password succesfully changed</p>
    </div>
    </div>
{% endblock %}

templates/user/password_change_form.html
{% extends parent_template|default: "user/base_user.html" %}
{% block title %}
    {{ block.super }} - Change password form
{% endblock %}

{% block content %}
    <div class="row">
    <div class="offset-by-two eight columns">
        <form action="dj-auth:pw-change" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Change Password</button>
        </form>
    </div>
    </div>
{% endblock %}

templates/user/password_reset_complete.html
{% extends parent_template|default:"user/base_user.html" %}
{% block title %}
{{ block.super }} - Reset Password
{% endblock %}

{% block content %}
    <div class="row">
    <div class="offset-by-two eight columns">
        <p>Your password has been reset</p>
        <p>Log in with your new password</p>
        {% include "user/login_form.html" %}
    </div>
    </div>
{% endblock %}

templates/user/password_reset_confirm.html
{% extends parent_template|default:"user/base_user.html" %}
{% block title %}
{{ block.super }} - Reset Password
{% endblock %}

{% block content %}
    <div class="row">
    <div class="offset-by-two eight columns">
        {% if validlink %}
            <p>Enter your new password bellow</p>
            <form action="{{ request.path }}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button-primary" type="submit">Save</button>
            </form>
        {% else %}
            <p>This link is no longer valid</p>
            <p>Please request a new reset email <a href="{% url 'dj-auth:pw_reset_start' %}">from here</a>. </p>
        {% endif %}
    </div>
    </div>
{% endblock %}

templates/user/password_reset_form.html
{% extends parent_template|default:"user/base_user.html" %}
{% block title %}
    {{ block.super }} - Reset Password
{% endblock %}

{% block content %}
    <div class="row">
    <div class="offset-by-two eight columns">
        <div class="center">
            <p>Reset password</p>
        </div>
        <form action="{% url 'dj-auth:pw_reset_start' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Reset steps</button>
        </form>
    </div>
    </div>
{% endblock %}

templates/user/password_reset_sent.html
{% extends parent_template|default:'user/base_user.html' %}
{% block title %}
{{ block.super }} - Password Reset Sent
{% endblock %}

{% block content %}
    <div class="row">
    <div class="offset-by-two eight columns">
        <p>Information for password reset sent by email</p>
        <p>Please also check you spam box</p>
    </div>
    </div>
{% endblock %}

templates/user/resend_activation.html
{% extends parent_template|default:"user/base_user.html" %}
{% block title %}
{{ block.super }} - Resend Activation Email
{% endblock %}

{% block content %}
<div class="row">
<div class="offset-by-two eight columns">
<div class="center">
<p>Resend the activation email</p>
</div>
<form action="{% url 'dj-auth:resend_activation' %}" method="post">
<button type="submit"> Resend Activation Email</button>
</form>
</div>
</div>

{% endblock %}

templates/user/user_activate.html
{% extends parent_template|default:'user/base_user.html' %}
{% block title %}
{{ title.super }} - Account Created
{% endblock %}

{% block content %}
    <div class="row">
    <div class="offset-by-two eight columns">
        <p>The activation link is no longer valid</p>
    </div>
    </div>
{% endblock %}

templates/user/user_confirm_delete.html
{% extends parent_template|default:"user/base_user.html" %}
{% block title %}
{{ block.super }} - Disable Account
{% endblock %}

{% block content %}
    <div class="row">
    <div class="offset-by-two eight columns">
        <p>Disable your account o this site</p>
        <form action="{% url 'dj-auth:disable' %}" method="post">
            {% csrf_token %}
            <button type="submit">Disable Account</button>
        </form>
    </div>
    </div>
{% endblock %}

templates/user/user_create_done.html
{% extends parent_template|default:'user/base_user.html' %}
{% block title %}
{{ title.super }} - Account Created
{% endblock %}

{% block content %}
    <div class="row">
    <div class="offset-by-two eight columns">
        <p>Account has been created</p>
        <p>Please verify your email for the activation link</p>
    </div>
    </div>
{% endblock %}